spring:
  application:
    name: 01-Mini-Project
  datasource:
    url: jdbc:h2:mem:mini_db
    username: mini-project
    password: aman
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

mini-project:
    messages:
        planSaveSucc: Plan Saved Successfully
        planSaveFail: Plan Saved Failed
        planUpdateScc: Plan Update Successfully
        planUpdateFail: Plan Updation Failed
        planDeleteSucc: Plan Deleted Successfully
        planDeleteFail: Plan Failed to Deleted
        planStatusChange: Plan Status Changed Successfully
        planStatusChangeFail: Plan Status Change Failed

